### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by elcritch** [mafm/ledger.fs#1]
Fun little library! I'm working at a small company on some simple financial forecasting for customer accounts. Instead of reinventing the wheel it'd be nice to build on your work. Any chance you'd be up for adding an MIT or Apache license? We'd like to contribute back bug fixes and the like but it'll need to run in our Web pages, so we'd need a permissive license. Currently I'm wanting to try transpiling F# to JS using FunScript to allow dynamic re-calcs of budget forecasts.

**Comment by mafm** [comment]
You're very welcome to use this code under the MIT license. I've just added a MIT license file to the repo.

In next month I expect to add multi-currency and multi-entity support to this, but probably won't do anything else other than refactor & bug fixes after that.
